[project]
name = "halstead-complexity"
version = "0.1.0"
description = "Measure Halstead code complexity"
readme = "README.md"
license = "MIT"
authors = [
    { name = "EpicAlbin03" }
]
keywords = ["halstead", "code complexity"]
requires-python = ">=3.12"
dependencies = [
    "confz>=2.1.0",
    "platformdirs>=4.4.0",
    "tree-sitter>=0.25.2",
    "typer>=0.19.2",
]

[project.scripts]
hc = "halstead_complexity.cli:app"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "pytest>=8.4.2",
]
